functions.js, index.js
Reverts James-Hackett/AwF-Bot#1
does not work, mainly the functions.js file. check discord to see why
=> Revert "Added two (pretty large) features. See description."

README.md, filterBan.js, functions.js, index.js, longMessages.js
Moved the message sending into a function in functions.js so it can be used to send a command to a single Factorio server. Also added a +help command for admins to use to get a list of commands they can use
=> Allows sending commands to all Factorio servers or a single server

index.js, serversetup.py
The issue: https://discordapp.com/channels/548410604679856151/718084746693050459/749323862193471519 (awf.yt discord server). Also why do you not have enters at the end of files, switch to LF instead of CRLF
=> maybe fixed the issue Windsinger found (see desc)

README.md, requirements.txt, serversetup.py
When run, serversetup.py now works according to what is said about it in README.md
=> Updated serversetup.py to backup the latest save and remove the save files

functions.js, index.js
This should fix the issue mentioned in #9 . On lines [50, 56], the command is being sent **without the username**, therefore in the format `/whisper oof2win2 hi`. On line [82], the message is being sent **with the username**, however, so in the format `oof2win2: /whisper oof2win2 hi`. Line [61] intentionally is `sendToAll(message, 1)` due to the fact that the 1 tells the function sendToAll() to send it **with the username**. On lines [50 and 56], the code is `sendToAll(message, 0)`. The 0 here means that the message is supposed to be sent **without the username**.
I have used the same solution as on line [37 and 38], where the message is not sent to the Factorio:
The image above is the screenshot from Discord, where there are messages sent: `Jammy say hi` and `Jammy work`.
The image above …
=> Fixing the issue Wind mentioned

commands/basic/faq.js, commands/faq/faq.js, longMessages.js
I don't know where to put the longMessages.js file at it is not a command, so I just left it in the root directory. The commands should work, code taken from help.js
=> FAQ commands may have been fixed to work with the new command system, 1 per file.

commands/basic/faq.js, longMessages.js
Fixed the `?faq` command. Tested and works
=> Fixed the faq command

commands/basic/faq.js, events/guild/message.js, longMessages.js
Added reacting to message using SOON emoji if it includes 'soon'
=> Added #20 (soon emoji)

commands/factorio/restoreSave.js, functions.js
Reverts James-Hackett/AwF-Bot#27
=> Revert "maybe fixed factorio saves"

commands/factorio/onlineplayers.js, functions.js
Fixed online players with promises and a promise.all()
=> Fixed RCON commands when failed, fixed online players

chatFormat.js, commands/moderator/rconcmd.js, commands/moderator/rconcmdall.js, functions.js, index.js
This PR is focused on messaging unlinked people to link themselves if they join a server and they aren't linked yet
Also changed `rconCommand` function to not have the `message` parameter, as it wasn't used
=> Auto-message & discord invite on join

README.md, chatFormat.js, commands/moderator/rconcmdall.js, functions.js, index.js, package.json
This PR is a feature addition to make stuff from the AwF scenario compatible, such as database integration, the new `/linkme` command etc.
* The ban reasons to the Moderators channel is now fixed, it sends with spaces instead of commas
* When people join, the bot checks if they should be receiving a role, if yes, gives it to them
* probably some other stuff, forgot most of it (my goldfish memory)
=> [FEATURE] AwF Scenario integration

functions.js
There was a bug in the `getServerFromChannelInput` function, as it was a `.map`, so it returned an **array**, not a single value. This has been fixed by not using a `.map` but a `for` loop, which doesn't have these problems
=> Bug fixed!

functions.js
There was a bug that player roles would go `n!` deep, `n` being the number of times a player joined. This caused large errors for linked players (with the new method), which was thankfully nobody except me. The role object of the player would look like [this](https://cdn.discordapp.com/attachments/718084746693050459/785201399251730433/Screenshot_2020-12-06_at_18.49.47.png), even though it should've been only the first two roles (Veteran, Member). This has been fixed in this PR.
=> [BUGFIX] Roles going n! deep

.gitignore, commands/factorio/fstatsserver.js, commands/factorio/serverstatus.js
This PR is a suggestion by Wilku, it adds more in-depth server statistics. Below is the image of the old  and new statistics respectively
*Image of statistics before*
*Image of statistics now*
Closes #65.
=> In depth server statistics

.gitignore, chatFormat.js, commands/moderator/resetserver.js, commands/moderator/startserver.js, events/guild/message.js, examples/command.example.js, examples/db.example.js, examples/djs.example.js, functions.js, index.js, package-lock.json, package.json
- Accepts the flag `--scenario NAME`. The scenario must be in the server's `scenarios` folder, otherwise, Factorio startup will 99% crash (but the bot won't) This works as `--start-server-load-scenario NAME` flag on the `./bin/x64/factorio` executable
- When a .json file is attached to the message, it automatically tries loading the file as the server's map gen settings (i.e. startup flag `--map-gen-settings FILE` on the `./bin/x64/factorio` executable)
There is a new folder, `./temp` in the bot's root directory. Files can be added and are automatically wiped upon bot startup. To generate a random filename (security reasons & so files don't write themselves over), use:
```js
const Str = require("@supercharge/strings");
let randomFileName = Str.random();
```
Resolves #64
=> ✨ Reset Servers from Discord ✨

chatFormat.js, commands/factorio/fstatsserver.js, commands/factorio/onlineplayers.js, commands/moderator/rconcmd.js, commands/moderator/rconcmdall.js, commands/moderator/reconnectrcon.js, functions.js, utils/rcon-connection.js
This PR has the main feature of a new class, `RconConnectionManager` (found in `./utils/rcon-connection.js`), which allows for a continuous RCON connection. It has auto-reconnect upon failure (only 1 attempt at reconnecting). To reconnect on-demand, the command `?reconnectrcon` can be used.
This thereby resolves #59
=> Continuous RCON connection

commands/factorio/linkme.js, commands/moderator/getfactorioroles.js, commands/moderator/givefactoriorole.js, commands/moderator/removefactoriorole.js, config/messages.json, events/client/ready.js, functions.js, index.js, package-lock.json, package.json, utils/cache-manager.js
Adds linking support that was mentioned in #68 but also has backwards compatibility for the old system for servers that still run on it. This is also integrated from the side of [the scenario](https://github.com/oof2win2/AwF-Scenario)
=> New linking support

.github/workflows/jsdoc.yml, base/Comfy.js, base/Prometheus.js, commands/Factorio/onlineplayers.js, commands/Moderation/rconcmd.js, helpers/fifo-handler.js, helpers/functions.js, helpers/rcon.js, helpers/serverHandler.js, helpers/serverUPSHandler.js, jsdoc.config.js, package-lock.json, package.json
Some basic documentation &  a workflow to create docs on push to master.
=> Documentation

.github/workflows/jsdoc.yml, Gruntfile.js, docs-parser.js, jsdoc.config.js, package-lock.json, package.json
Docs workflow. Docs are now compiled with Grunt and [`jsdoc-to-markdown`](https://github.com/jsdoc2md/jsdoc-to-markdown/) on push to master. Need to be manually added to thee Grunt file so they are generated, otherwise the file is ignored as I wasn't able to get that working.
=> Fix for the docs workflow

base/Command.js, base/Tails.js, commands/Administration/resetserver.js, commands/Administration/rollback.js, commands/Administration/startserver.js, commands/Administration/stopserver.js, commands/General/help.js, commands/Moderation/rconcmd.js, commands/Moderation/rconcmdall.js, events/message/message.js, helpers/serverHandler.js
Added custom role permissions so moderators can use advanced commands and not require the `ADMINISTRATOR` discord permission.
=> Custom role permissions

src/base/GrafanaHandler.ts, src/commands/Administration/updatescenarios.ts, src/commands/Factorio/statsg.ts, src/config.example.ts, src/helpers/functions.ts, src/helpers/serverHandler.ts, src/index.ts, src/types.ts, tsconfig.json
- Command to pull scenario changes
- Fix graftorio not collecting correctly
- fixed death message displaying `PLAYER:` instead of playername
- Rounded off points and time on stats message
=> update scenarios command

src/base/GrafanaHandler.ts, src/commands/Administration/getlogs.ts, src/commands/Administration/resetserver.ts, src/commands/Administration/rollback.ts
- Actually use provided line limit provided in `?getlogs`
- Back up the latest save and not the first save found in `?resetserver`
- Some other stuff as well
=> General fixes

src/commands/Factorio/linkme.ts, src/events/message/messageUpdate.ts
Send the Ron Swanson "I am really proud of you" gif when a user
successfully links
=> feat(linkme): send gif on successful linking

package-lock.json, package.json, src/base/Comfy.ts, src/base/GrafanaHandler.ts, src/commands/Factorio/onlineplayers.ts, src/commands/Factorio/statss.ts, src/commands/Moderation/rconcmd.ts, src/commands/Moderation/rconcmdall.ts, src/helpers/rcon.ts, src/helpers/serverHandler.ts, src/helpers/serverUPSHandler.ts
Implement the better rcon client that automatically reconnects from FAGC
=> feat(rcon): better rcon client from FAGC

src/helpers/fifo-handler.ts
Remove possibility to inject commands through discord chat and username starting from `/command dowhatiwant;`
=> forbid injection of `/` through custom username
